// <auto-generated />
using BookSalesWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BookSalesWebApp.Migrations
{
    [DbContext(typeof(BookSalesWebAppContext))]
    [Migration("20171210231349_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookSalesWebApp.Models.Book", b =>
                {
                    b.Property<int>("isbn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("author");

                    b.Property<decimal>("listPrice");

                    b.Property<string>("releaseDate");

                    b.Property<string>("title");

                    b.HasKey("isbn");

                    b.ToTable("books");
                });
#pragma warning restore 612, 618
        }
    }
}
