// <auto-generated />
using BookSalesWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BookSalesWebApp.Migrations
{
    [DbContext(typeof(BookSalesWebAppContext))]
    [Migration("20171211063218_Customer")]
    partial class Customer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookSalesWebApp.Models.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("VARCHAR(13)")
                        .HasMaxLength(13);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(1000)")
                        .HasMaxLength(1000);

                    b.Property<decimal>("ListPrice");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("ISBN");

                    b.ToTable("books");
                });

            modelBuilder.Entity("BookSalesWebApp.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Address2")
                        .HasColumnType("NVARCHAR(300)")
                        .HasMaxLength(300);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(300)")
                        .HasMaxLength(300);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(300)")
                        .HasMaxLength(300);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(300)")
                        .HasMaxLength(300);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(300)")
                        .HasMaxLength(300);

                    b.HasKey("ID");

                    b.ToTable("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
